import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { adminConfigured, authenticated, newSession, sameOrigin } from '../src/lib/admin.ts';
import { channelFields, deleteChannel, listChannels, updateFields, uploadImage, validLink } from '../src/lib/cloudinary.ts';

process.env.ADMIN_PASSWORD = 'test-password-for-tests-only';
process.env.ADMIN_SESSION_SECRET = 'test-secret-for-tests-only-1234567890';
process.env.CLOUDINARY_CLOUD_NAME = 'test-cloud';
process.env.CLOUDINARY_API_KEY = 'test-key';
process.env.CLOUDINARY_API_SECRET = 'test-secret';
process.env.ADMIN_PASSWORD = '1234567';
assert.equal(adminConfigured(), false);
process.env.ADMIN_PASSWORD = 'Test1234';
assert.equal(adminConfigured(), true);
const token = newSession();
const context = value => ({ cookies: { get: () => ({ value }) } });
assert.ok(authenticated(context(token)));
assert.equal(authenticated(context(token + 'tampered')), false);
assert.equal(authenticated(context('0.signature')), false);
process.env.ADMIN_PASSWORD += '-changed';
assert.equal(authenticated(context(token)), false);
assert.equal(sameOrigin(new Request('https://example.com/api', { headers: { origin: 'https://evil.example' } })), false);
assert.ok(sameOrigin(new Request('https://example.com/api', { headers: { origin: 'https://example.com' } })));
assert.ok(validLink('https://t.me/+qBphnusW2CIwNjFh'));
assert.equal(validLink('https://t.me.evil.example/+abc'), false);
assert.equal(validLink('javascript:alert(1)'), false);
const form = new FormData();
for (const [key, value] of Object.entries({ href: 'https://t.me/+abc123', order: '2', theme: 'blue', imageAlt: 'Una imagen | ejemplo = prueba', enabled: 'true' })) form.set(key, value);
const fields = channelFields(form);
assert.equal(fields.imageAlt, 'Imagen del canal de Telegram');
form.set('order', '-1'); assert.throws(() => channelFields(form));

let calls = [];
globalThis.fetch = async (url, options) => {
  calls.push({ url: String(url), options });
  return Response.json({ resources: [{ public_id: 'pqsr/channels/test', secure_url: 'https://res.cloudinary.com/test/image/upload/v1/a.jpg', context: { custom: { link: 'https://t.me/+abc123', order: '2', enabled: 'false', theme: 'blue' } } }] });
};
const channels = await listChannels();
assert.equal(channels[0].enabled, false);
assert.equal(channels[0].href, 'https://t.me/+abc123');
assert.ok(calls[0].url.includes('prefix=pqsr%2Fchannels%2F'));
await assert.rejects(() => deleteChannel('another-project/image'));
await assert.rejects(() => uploadImage(new Blob(['<svg/>']), fields));
calls = [];
await updateFields('pqsr/channels/test', { ...fields, imageAlt: 'Una imagen | ejemplo = prueba' });
const body = calls[0].options.body;
assert.ok(body.get('context').includes('enabled=true'));
assert.ok(body.get('context').includes('\\|'));
const params = [...body.entries()].filter(([key]) => !['api_key', 'signature'].includes(key)).sort(([a], [b]) => a.localeCompare(b)).map(([key, value]) => `${key}=${value}`).join('&');
assert.equal(body.get('signature'), createHash('sha1').update(params + 'test-secret').digest('hex'));
await deleteChannel('pqsr/channels/test');
assert.ok(calls[1].url.endsWith('/image/destroy'));
const image = new Blob([await readFile(new URL('../src/assets/images/images/photo_2026-10-06_22-01-26.jpg', import.meta.url))]);
await uploadImage(image, fields, 'pqsr/channels/test');
assert.ok(calls[2].url.endsWith('/image/upload'));
assert.equal(calls[2].options.body.get('public_id'), 'pqsr/channels/test');
assert.ok(calls[2].options.body.get('context').includes('link=https://t.me/+abc123'));
assert.equal(calls[2].options.body.get('overwrite'), 'true');
globalThis.fetch = async () => new Response('failed', { status: 401 });
await assert.rejects(() => listChannels(), /Cloudinary/);
console.log('OK: sesiones, expiración, origen, enlaces, metadatos firmados, aislamiento de tarjetas, formatos y fallos de Cloudinary. Sin llamadas externas.');
